### PR TITLE
remove first_value and map_value, refactor to use idiomatic traject

### PR DESCRIPTION
**Pull request by barmintor**
Trying to remove some dead code where possible while prepping 7.0rc.

### CODE REVIEW

**Comment by barmintor** [comment]
@billdueber @jrochkind does this better align the default indexer model with Traject 3 idioms? I'm trying to remove the redundant extensions from 6.x before we mint an RC here.

**Comment by jrochkind** [comment]
@barmintor oops, before I saw this tag I went and commented here: https://github.com/projectblacklight/blacklight-marc/pull/76#issuecomment-433925529

Does that answer your question?

**Comment by jrochkind** [comment]
I don't think you need `map_value` at all anymore, the native traject `translation_map` will now do what you are doing?

Otherwise, if I understand what you are doing -- yes, moving from the arguments to extract_marc, to additional "macros" (ie methods returning procs) added on to the end of the `to_field` call, is traject 3.0's current recommended thing to do. Among other things, it makes clearer shareable code/API between MARC and other-than-MARC use cases. 

The old arguments to `extract_marc` are not planned to go away though, they are "soft deprecated" with no particular timeline for removal, if ever. So you don't _gotta_ change em. But changing em will match traject's current documentation and recommendations, and perhaps make it easier to share code with other traject users.

**Comment by jrochkind** [comment]
Ah, you may be spec'ing map_value because it is deprecated but still present, and are on the same tip. Cool. https://github.com/projectblacklight/blacklight-marc/pull/79/files#diff-07b648253c460691ed69db4e8916bc64R83

You could provide a method signature for map_value that lets you do `map_value(one, two)` instead of `map_value([one, two])` if you want.  That is what the built-in traject 3.0 `translation_map` does, using an `*args` argument.

**Comment by barmintor** [comment]
@jrochkind the reason I'm reluctant to pull it in one fell swoop is that the merge priority is, if I read correctly, the reverse from the traject behavior - so moving to the syntax is a change, but removing it might introduce subtle bugs.

**Comment by jrochkind** [comment]
Oh, I didn't notice that the priority was different, oops! I meant to make it match, that blacklight-marc needed it was significant motivation for including the feature in traject.  It didn't occur to me that there could be different orders of operation, it seemed obvious to me that:

    translation_map(one, two, three)

should be handled like:

   one.merge(two).merge(three)

Obviously (ha) what's obvious is not in fact obvious. `map_values` does it the opposite? Okeydokey. 

If you are still supporting the original old behavior anyway, I think it still might be worth considering _not_ making map_values do a new thing that will be immediately deprecated. But your call. You might want to make the deprecation message (new `map_values` still results in deprecation message?) have an explicit example of how to do it with traject core, or link to a URL with an example, or whatever. Maybe also mentioning the reversed order of arguments.

**Comment by barmintor** [comment]
Yes, the legacy behavior is better understood as a cascade of defaults than as a merge.

That's a good point about the deprecation message - maybe I can make the remaining wrapper thinner still by just having it reverse the argument.

**Comment by jrochkind** [comment]
Makes sense. But nobody is going to get the new `map_values` without changing their code anyway, right? If the old one is deprecated too....   anyway, your call if you think this way will reduce errors, just not clear to me. :)

Sorry I/we didn't notice the order-mismatch before traject 3.0.0 final, I would have considered making it match, since bl-marc was the main motivated use case. (Although it still seems backwards to me! But a lost cause at this point, it's done!)

**Comment by barmintor** [comment]
Spending some time going through dependent projects, and not finding any uses of `map_value`. I'm going to push a commit that just removes it.

**Comment by barmintor** [comment]
(and open a ticket for a 6.x deprecation release)

**Pull request merged**
